version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/aws-code-pandemic-pictures
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStart:
    - location: deployScripts/start_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: deployScripts/stop_server.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: deployScripts/install.sh
      timeout: 300
      runas: ec2-user