version: 0.0
os: linux
files:
  - source: /
    destination: /home/aws-code-deploy-pandemic-pictures
hooks:
  ApplicationStart:
    - location: deployScripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: deployScripts/stop_server.sh
      timeout: 300
      runas: root
